set -g status on

# prefix
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# change the delay
set -sg escape-time 100

set -g default-terminal "screen-256color"
set -g terminal-overrides 'xterm*:colors=256'

# default statusbar colors
set-option -g status-bg black
set-option -g status-fg brightblue
# set-option -g status-attr default
set-option -g status-style fg=brightblue,bg=black

# default window title colors
# set-window-option -g window-status-fg brightblue
set-window-option -g window-status-style fg=brightblue,bg=default
# set-window-option -g window-status-bg default
#set-window-option -g window-status-attr dim

# active window title colors
#set-window-option -g window-status-current-fg brightred
#set-window-option -g window-status-current-bg default
#set-window-option -g window-status-current-attr bright
set-window-option -g window-status-current-style fg=brightred,bg=default

# pane border
# set-option -g pane-border-fg black #base02
# set-option -g pane-active-border-fg cyan
set-option -g pane-border-style fg=black
set-option -g pane-active-border-style fg=cyan

# message text
# set-option -g message-bg black #base02
# set-option -g message-fg yellow
set-option -g message-style fg=yellow,bg=black

# pane number display
set-option -g display-panes-active-colour red
set-option -g display-panes-colour blue

# clock
set -g clock-mode-colour gray
set -g clock-mode-style 24

# set the window index
set-option -g base-index 1
# set the pane index
set-window-option -g pane-base-index 1

# source-file
bind-key r source-file ~/.tmux.conf \; display "Reloaded:)"

# split-window
# vertical split
unbind '"'
bind-key - split-window -v -c "#{pane_current_path}"
# horizontal split
unbind %
bind-key | split-window -h -c "#{pane_current_path}"

# select-pane
bind-key -r k select-pane -U
bind-key -r j select-pane -D
bind-key -r h select-pane -L
bind-key -r l select-pane -R

# resize-pane
bind-key ^h resize-pane -L 5
bind-key ^j resize-pane -D 5
bind-key ^k resize-pane -U 5
bind-key ^l resize-pane -R 5

# refresh interval in seconds of status bar
set -g status-interval 10

setw -g monitor-activity on
set -g visual-activity on

# vi mode
set-option -g status-keys vi
set-window-option -g mode-keys vi

# mouse mode
# Incompatible Changes for v2.1
set-window-option -g mouse on
bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'copy-mode -e'"

bind-key c neww -c "#{pane_current_path}"
bind-key C command-prompt -p 'change path:' 'neww -c %%'
bind-key m command-prompt -p 'which manual:' "split-window 'exec man %%'"

# history-limit
set -g history-limit 50000

set -g @plugin 'tmux-pluigns/tpm'
set -g @plugin 'dracula/tmux'
set -g @dracula-plugins "time"
set -g @dracula-show-left-icon 'λ'
set -g @dracula-colors "
white='#f8f8f2'
gray='#44475a'
dark_gray='#282a36'
light_purple='#bd93f9'
dark_purple='#6272a4'
cyan='#8be9fd'
green='#44475a'
orange='#ffb86c'
red='#ff5555'
pink='#ff79c6'
yellow='#f1fa8c'
"
set -g @dracula-time-format "%F %R"
set -g @dracula-show-empty-plugins false
run '~/repo/github.com/tmux-plugins/tpm/tpm'
